### PR TITLE
Change Model to be a type family

### PR DESCRIPTION
**Pull request by isovector**
This PR changes Model from a fundep to a type family, and adds some obviously missing instances. The rationale is below.

---

The encoding of `Model` as a fundep is somewhat problematic, as it gives us nothing to "hold on to" when wanting to give the types of function denotations.

For example, if we want to encode the following denotation in haskell:

```haskell
data System
μ System = (Id, M.Map Id Entity)

data Setter 
μ Setter = Entity -> Maybe Entity

data Query a 
μ Query a = System -> Entity -> Maybe a

setEntity :: Id -> Setter -> System -> System

newEntity :: Setter -> System -> (System, Id)
μ newEntity set sys =
  let (ix, m) = μ sys
   in (setEntity ix set (φ (ix + 1, m)), ix)  -- φ is the inverse of μ
```

We can model the μ for the types via `instance Model T (μ T)`. However, because there is no guarantee that φ exists, the only compositional definition we can give for `μ newEntity` is to replace everything (the arguments, result, and other calls in the design) with their models:

```haskell
m_newEntity m_set m_sys =
  let (ix, m) = m_sys
   in (m_setEntity ix m_set (ix + 1, m), ix)
```

But the type of `m_newEntity` is now:

```haskell
(Entity -> Maybe Entity) -> (Id, M.Map Id Entity) -> ((Id, M.Map Id Entity), Id)
```

which bears no resemblance to the type of `newEntity`, leaks the model, and it makes it harder to change our minds later. By instead changing the fundep of Model to a type family, we can instead give it the much nicer type:

```haskell
ModelOf Setter -> ModelOf System -> ModelOf (System, Id)
```

### CODE REVIEW

**Comment by conal** [comment]
Looks good. What sort of testing has been done for these changes?

**Comment by isovector** [comment]
I'm not sure, though CI should be able to tell us!  But it doesn't seem to have picked up this PR for some reason. @conal, @sjakobi, do either of you know why CI has missed this?

**Comment by sjakobi** [comment]
Travis notifications on GitHub have been rather unreliable in the last few months. [The job for this PR](https://travis-ci.org/github/conal/checkers/builds/682746075) has passed though.

**Comment by sjakobi** [comment]
Oh, wait. That job doesn't seem to be for the current HEAD commit on your branch. Could you re-push, @isovector?

**Comment by isovector** [comment]
This turns out to not really solve the problem, which is that modeling isn't particularly expressible in Haskell. 

In the rationale presented above, `m_newEntity` is a sufficiently good model for `newEntity`; but it's not something that can be derived in Haskell --- it requires the non-denotational operation of substituting `m_setEntity` for `setEntity` in the definition of `m_newEntity`.

The problem with the model class is that it conflates the modeled type with a denotational transformation to produce that type. This is fine for simple types, but fails for functions! If we want `m_newEntity` to have simultaneously have types `ModelOf Setter -> ModelOf System -> ModelOf (System, Id)` (given above) and `ModelOf (Setter -> System -> (System, Id))`, then it requires the following model instance:

```haskell
instance (Model a, Model b) => Model (a -> b) of
  type ModelOf (a -> b) = ModelOf a -> ModelOf b
  model = -- unimplementable
```

Why unimplementable? Because the variance here is wrong; in order to do this we need an `unmodel :: ModelOf a -> a` operation, which is impossible unless the `model` function is surjective. Surjectivity is a _big_ ask, and AFAICT completely precludes continuous codomains of the meaning functor.

**Comment by conal** [comment]
I agree with your analysis of `Model` for functions, @isovector, i.e., that we’d need `model` to be surjective at least (and injective as well, to eliminate ambiguity). On the other hand, homomorphisms & commutative diagrams don’t generally require inversion, but instead look like `meq1` in `Test.QuickCheck.Checkers`.

I don’t see any uses of `Model` in checkers, and I don’t remember the motivation.

**Pull request closed without merging**
